name 'effortless_compliance'
maintainer 'Davin Taddeo'
maintainer_email 'davin@chef.io'
license 'All Rights Reserved'
description 'Contains InSpec profiles and logic for doing compliance scans against systems'
version '0.1.1'
chef_version '>= 17.5'
